[project]
name = "valenci-anndata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anndata>=0.11.4",
    "polis-client",
]

[tool.uv.sources]
polis-client = { git = "https://github.com/patcon/polis-client" }
